CREATE TABLE card_categories (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  card_id INT NOT NULL UNIQUE REFERENCES cards(id) ON DELETE CASCADE,
  category_id INT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);