CREATE TABLE card_comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  card_id INT NOT NULL REFERENCES cards(id) ON DELETE CASCADE,
  membership_id INT NOT NULL REFERENCES memberships(id) ON DELETE CASCADE,
  body TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);