CREATE TABLE boards (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  organization_id INT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name VARCHAR(255) NOT NULL,
  icon VARCHAR(255) NOT NULL DEFAULT 'pyramid',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);